---
# tasks file for openbox-archlinux

- pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - feh
    - launchy
    - menumaker
    - openbox
    - plank
    - xorg-xinit
    - xterm
  tags:
    - openbox

- name: auto start openbox
  become: no
  blockinfile:
    path: /home/{{ ansible_ssh_user }}/.xinitrc
    create: yes
    block: |
      export DISPLAY=:0.0
      exec openbox-session
  tags:
    - openbox

- name: copy configuration
  become: no
  shell: cp -R /etc/xdg/openbox /home/{{ ansible_ssh_user }}/.config/
  tags:
    - openbox

- name: configure plank
  become: no
  template:
    src: templates/plank-settings.j2
    dest: /home/{{ ansible_ssh_user }}/.config/plank/dock1/settings
  tags:
    - config
    - openbox
    - plank

- name: add apps launcher to plank
  become: no
  template:
    src: templates/plank-launcher.j2
    dest: /home/{{ ansible_ssh_user }}/.config/plank/dock1/launchers/{{ item }}.dockitem
  with_items: "{{ launchers }}"
  tags:
    - dev

- name: autoload dock, launcher, and set wallpaper
  become: no
  blockinfile:
    path: /home/{{ ansible_ssh_user }}/.config/openbox/autostart
    block: |
      # -- load the dock Plank
      plank &
      # -- load the app laucher Launchy
      launchy &
      # -- locad the wallpaper image
      feh --bg-scale ~/.wallpapers/darth-vader-01.jpg &
  tags:
    - config
    - launchy
    - openbox
    - plank

- name: copy theme files
  become: no
  copy:
    src: themes/Mistral
    dest: /home/{{ ansible_ssh_user }}/.themes
    mode: 0644
    directory_mode: 0755
  tags:
    - config
    - openbox

- name: configuring wallpaper background
  become: no
  copy:
    src: wallpapers/
    dest: /home/{{ ansible_ssh_user }}/.wallpapers/
    mode: 0644
    directory_mode: 0755
  tags:
    - config
    - openbox

- name: Install python lxml module needed by the ansible xml module
  pip:
    name: lxml
    state: latest
  tags:
    - config
    - openbox

- name: configure Openbox for best performance
  become: no
  xml:
    path: /home/{{ ansible_ssh_user }}/.config/openbox/rc.xml
    xpath: /x:openbox_config/{{ item.xpath }}
    value: "{{ item.value }}"
    namespaces:
      x: http://openbox.org/3.4/rc
  with_items: "{{ openbox_config }}"
  tags:
    - config
    - openbox
